name: Backend CI

on:
  push:
    branches:
      - dev
      - 'feature/**'
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - dev
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. Checkout du code
      - name: Checkout repo
        uses: actions/checkout@v6.0.1

      # 2. Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3. Cache Maven
      - name: Cache Maven Local Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 4. Build + tests
      - name: Build the project
        working-directory: backend
        run: mvn -B clean verify

      # 5. Packaging
      - name: Package the backend
        working-directory: backend
        run: mvn -B package -DskipTests
# # backend.ci.yaml (minimal pour test)
# name: CI Backend Placeholder

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Build Docker Image
#         run: docker build -t backend ./backend
#       - name: Login to Registry
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Push Image
#         run: docker push backend
