name: Chatbot CI

on:
  push:
    branches:
      - develop
      - feature/**
    paths:
      - 'chatbot/**'
  pull_request:
    branches:
      - develop
      - feature/**
    paths:
      - 'chatbot/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r chatbot/requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        cd chatbot
        pytest tests -v --cov=. --cov-report=term-missing

    - name: Lint with flake8 (optional)
      continue-on-error: true
      run: |
        pip install flake8
        flake8 chatbot/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test summary
      run: |
        echo "✅ Tests du chatbot terminés avec succès"
        echo "🔬 Branche: ${{ github.ref_name }}"
