name: Chatbot CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ develop , feature  ]
  #   paths:
  #     - 'chatbot/**'
  # pull_request:
  #   branches: [ develop ]
  #   paths:
  #     - 'chatbot/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd chatbot
          pip install -r requirements.txt

      - name: Lint with flake8 (optional) # Un linter analyse le code pour trouver des erreurs, des problèmes de style et des mauvaises pratiques.

        run: |
          pip install flake8
          cd chatbot
          flake8 app.py --count --select=E9,F63,F7,F82 --show-source --statistics

        continue-on-error: true
      - name: Build Docker image
        run: |
          cd chatbot
          docker build -t gemini-chatbot:${{ github.sha }} .
          docker tag gemini-chatbot:${{ github.sha }} gemini-chatbot:latest

      - name: Test Docker image
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          docker run --rm -e GOOGLE_API_KEY=$GOOGLE_API_KEY gemini-chatbot:latest python -c "import google.generativeai as genai; print('Import successful')"

      - name: Log in to Docker Hub (optional)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # si on veut pusher au dockerhub :)
      - name: Push to Docker Hub (optional)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag gemini-chatbot:latest ${{ secrets.DOCKER_USERNAME }}/gemini-chatbot:latest
          docker tag gemini-chatbot:latest ${{ secrets.DOCKER_USERNAME }}/gemini-chatbot:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/gemini-chatbot:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gemini-chatbot:${{ github.sha }}
